var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                        wwwwwwwx",
   "                                                                               x",
   "                                               0             xxxxxx            x",
   "                                               0                               x",
   "                                               0                               x",
   "                                               0                               x",
   "                                                     xxxx                      x",
   "                                              xxx                              x",
   "                                     xxxx                                      x",
   "     @                                                                         x",
   "  xxxxxxx                                                                      x",
   "  xxxxxxx                         00                                           x",
   "  xxxxxxx                                xxxx            000                   x",
   "  xxxxxxx        x=    x       x=      x         xxxx                          x",
   "  xxxxxxx        xxxxxxx       xxxxxxxxx                                       x",
   "  xxxxxxx                                                xxxxxx    p           x",
   "  xxxxxxx                                                                      x",
   "  xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  xxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
 ["                                                                                 ",
  "                                                                                 ",
  "                                                                                 ",
  "                                                                                 ",  
  "                                                      ww                         ",
  "                                            0                                    ",
  "                                           xxx                         xxx       ",  
  "                                                                                 ",
  "                                                      xxx                    xx  ",
  "                                    xx                                      0    ",
  "                       0                                                         ",
  "                                           xx                   xx             xx",  
  "                        xx                                                  0    ",
  "                                                                                 ",
  "                                    0                                            ",
  "                                 xx                                      xx      ",
  "                                                                                 ",  
  "                                                                  0              ",
  "                                       xx     0                                  ",
  "                                                                                 ",
  "                                                                                 ",
  "                                  0           xx                 xx              ",  
  "                                                                                0",
  "                                                                                 ",
  "                                  xx                                        xxx  ",
  "                                                                                 ",
  "                                               p                                 ",  
  "                        0                                           00           ",
  "                                                                                 ",
  "                       xxx                                         xxx           ",
  "                                                                                 ",
  "   @                                                                             ",  
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
 ["                                                                                 ",
  "  @                                                                               ",
  "xxxx                                                                             ",
  "                                            0                                    ",
  "                                           xxx                         xxx       ",  
  "                                                                                 ",
  "                                                      xxx                    xx  ",
  "                                    xx                                      0    ",
  "                       0                                                         ",
  "                                           xx                   xx             xx",  
  "                        xx                                                  0    ",
  "                                                                                 ",
  "                                    0                                            ",
  "                                 xx                                      xx      ",
  "                                                                                 ",  
  "                                                                  0              ",
  "                                       xx     0                                  ",
  "                                                                                 ",
  "                                                                                 ",
  "                                  0           xx                 xx              ",  
  "                                                                                0",
  "                                                                                 ",
  "                                  xx                                        xxx  ",
  "                                                                                 ",
  "                                               p                                 ",  
  "                        0                                           00           ",
  "                                                                                 ",
  "                       xxx                                         www           ",
  "         p                                                                       ",
  "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",  
  "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
